ARG BASE_IMAGE=mageops/raccoon-base-centos
FROM ${BASE_IMAGE} AS base-ansible

RUN yum -y install \
        python3 \
        python3-virtualenv \
        python3-pip

ARG RCN_ANSIBLE_BRANCH="master"

ENV MAGEOPS_ROOT="/opt/mageops" \
    MAGEOPS_ANSIBLE_BRANCH="${RCN_ANSIBLE_BRANCH}"

COPY mageops-bin/ $MAGEOPS_ROOT/bin/
RUN /usr/bin/bash $MAGEOPS_ROOT/bin/mageops-install